-- Restore authenticated slug/name SELECT on "Role" (member login fix).
--
-- Regression: 20260930000001_role_revoke_anon_read.sql ran
--   revoke all on "Role" from anon, authenticated;
-- intending to kill *anon* reads, but it also wiped the
--   grant select (slug, name) on "Role" to authenticated
-- that 20260927000001_role_read_columns_fix.sql had just established.
-- Login role resolution (resolveLoginRole / LoginPage) reads
-- MemberRole -> Role through the authenticated browser client, so without
-- this grant PostgREST returns 42501 "permission denied for table Role",
-- role resolution degrades, and the member session is cleared (the
-- /me/broadcasts 401 is collateral, not the cause).
--
-- SELECT-only: adds no write policy/privilege, so rls_invariants.sql
-- checks #1-#3 stay PASS; it re-enables exactly the two label columns that
-- check #7 permits. The dormant role_read_authenticated RLS policy becomes
-- live again, still SELECT-only. Anon stays revoked (no anon RLS policy
-- exists, so an anon grant would be inert anyway).
--
-- Pre-apply validation (run first; expect 0 rows):
--   select grantee, table_name, column_name, privilege_type
--   from information_schema.role_column_grants
--   where grantee = 'authenticated' and table_name = 'Role'
--     and privilege_type = 'SELECT';
-- Post-apply: exactly the (slug, name) rows must exist, nothing else:
--   select column_name from information_schema.role_column_grants
--   where grantee = 'authenticated' and table_name = 'Role'
--     and privilege_type = 'SELECT' order by column_name;
--   -- expect: name, slug
--
-- Down: revoke select on "Role" from authenticated;

grant select (slug, name) on "Role" to authenticated;